name: 'Issue Estimator'
description: 'Estimate time to complete issue (and all nested issues)'
inputs:
  user:
    description: 'User account name where projects are found'
    required: true
  token:
    description: 'Github token used to read issues and write to projects'
    required: true
outputs:
  total:
    description: 'Total estimated time to complete issues'
runs:
  using: 'node12'
  main: 'index.js'