name: 'Issue Estimator'
description: 'Estimate time to complete issue (and all nested issues)'
outputs:
  total:
    description: 'Total estimated time to complete issues'
runs:
  using: 'node12'
  main: 'index.js'